version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    environment:
      MTX_LOGLEVEL: debug
      MTX_WEBRTC_ICEHOSTNAT1TO1IPS: '["65.109.32.111"]'
      MTX_WEBRTC_ICESERVERS: '["stun:stun.l.google.com:19302","stun:stun.cloudflare.com:3478"]'
    networks:
      - coolify
    ports:
      - "8189:8189/udp" # ICE/UDP media. Required for WebRTC to flow.
    restart: unless-stopped

  mediamtx-edge:
    image: nginx:alpine
    container_name: mediamtx-edge
    depends_on:
      - mediamtx
    volumes:
      - ./nginx.d:/etc/nginx/conf.d:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.routers.sfu.rule=Host(`sfu.itagenten.no`)"
      - "traefik.http.routers.sfu.entrypoints=https"
      - "traefik.http.routers.sfu.tls=true"
      - "traefik.http.services.sfu.loadbalancer.server.port=80"
    networks:
      - coolify

networks:
  coolify:
    external: true
    name: coolify


