version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8890:8889" # External port 8890 → internal 8889 (avoid conflicts)
      - "8189:8189/udp" # ICE/UDP media. Required for WebRTC to flow.
    restart: unless-stopped


