version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    environment:
      MTX_LOGLEVEL: debug
      MTX_WEBRTC_ICEHOSTNAT1TO1IPS: '["65.109.32.111"]'
      MTX_WEBRTC_ICESERVERS: '["stun:stun.l.google.com:19302","stun:stun.cloudflare.com:3478"]'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.routers.sfu.rule=Host(`sfu.itagenten.no`)"
      - "traefik.http.routers.sfu.entrypoints=https"
      - "traefik.http.routers.sfu.tls=true"
      - "traefik.http.routers.sfu.middlewares=sfu-cors"
      - "traefik.http.services.sfu.loadbalancer.server.port=8889"
      - "traefik.http.middlewares.sfu-cors.headers.accesscontrolallowmethods=OPTIONS,POST,GET"
      - "traefik.http.middlewares.sfu-cors.headers.accesscontrolalloworiginlist=https://prekestudio.itagenten.no"
      - "traefik.http.middlewares.sfu-cors.headers.accesscontrolallowheaders=content-type,authorization"
      - "traefik.http.middlewares.sfu-cors.headers.accesscontrolmaxage=86400"
      - "traefik.http.middlewares.sfu-cors.headers.addvaryheader=true"
      - "traefik.http.routers.sfu-preflight.rule=Host(`sfu.itagenten.no`) && (Method(`OPTIONS`) && (PathPrefix(`/whip/`) || PathPrefix(`/whep/`)))"
      - "traefik.http.routers.sfu-preflight.entrypoints=https"
      - "traefik.http.routers.sfu-preflight.tls=true"
      - "traefik.http.routers.sfu-preflight.service=noop@internal"
      - "traefik.http.routers.sfu-preflight.middlewares=sfu-cors"
    networks:
      - coolify
    ports:
      - "8189:8189/udp" # ICE/UDP media. Required for WebRTC to flow.
    restart: unless-stopped

networks:
  coolify:
    external: true
    name: coolify


