FROM bluenviron/mediamtx:latest

# MediaMTX configuration via environment variables
# See: https://github.com/bluenviron/mediamtx#configuration

EXPOSE 8889
EXPOSE 8189/udp

# mediamtx is the default entrypoint/cmd

